version: 2  # Required by dbt to define model metadata, tests, and docs

models:
  - name: dim_listings_clean  # Applies to the dim_listings_clean model

    columns:

      - name: listing_id
        tests:
          - unique                  # Ensure no duplicates
          - not_null                # Ensure every row has a value

      - name: host_id
        tests:
          - not_null
          - relationships:          # Ensure it matches a host_id in the dim_hosts_cleansed model
              to: ref('dim_hosts_clean')
              field: host_id

      - name: room_type
        tests:
          - accepted_values:        # Only allow one of the listed room types
              values: [
                'Entire home/apt',
                'Private room',
                'Shared room',
                'Hotel room'
              ]
